### ISSUE TITLE
Unable to find LocatorListener class after importing library

### ISSUE THREAD

**Issue by dheeraj192** [RadiusNetworks/flybuy-android#12]
After setting up the project in Android using maven unable to find the LocatorListener class to implement as the class seems to be obfuscated.

<img width="1276" alt="Screen Shot 2021-02-24 at 10 01 06 AM" src="https://user-images.githubusercontent.com/5268748/108947844-45e17c80-7687-11eb-97b2-c4c46d0d42d1.png">

**Comment by botnerd** [comment]
We're taking care of fixing this, and it will be in the next SDK release.

**Comment by botnerd** [comment]
This has been fixed with the 2.0.1 release.
