### ISSUE TITLE
Documentation is not updated

### ISSUE THREAD

**Issue by hatched-mariusz** [RadiusNetworks/flybuy-android#22]
I see that 
```
FlyBuyCore#configure(application: android.app.Application, appTokenKey: kotlin.String)
``` 
Is deprecated and I should use 
<img width="744" alt="Screenshot 2023-07-18 at 14 26 42" src="https://github.com/RadiusNetworks/flybuy-android/assets/47123235/d6ca09f3-4c0c-4e8d-a21a-a3130f403eeb">
```
FlyBuyCore#configure(application: android.app.Application, withOptions)
```
Into documentation is the same: 
<img width="762" alt="Screenshot 2023-07-18 at 14 27 43" src="https://github.com/RadiusNetworks/flybuy-android/assets/47123235/647cd25b-2dcc-4b4b-8993-98d58c663a90">

But class ConfigOptions doesn't have the Builder: 
<img width="870" alt="Screenshot 2023-07-18 at 14 25 24" src="https://github.com/RadiusNetworks/flybuy-android/assets/47123235/b89ccace-8475-4493-8f88-a27793f11fae">

**Comment by hatched-mariusz** [comment]
The sample app use a deprecated method: 
https://github.com/RadiusNetworks/flybuy-android-example/blob/main/app/src/main/java/com/radiusnetworks/example/flybuy/ExampleApplication.kt 

```
FlyBuyCore.configure(this, "FLYBUY_APP_TOKEN")
```

**Comment by botnerd** [comment]
Thanks for reporting this. We'll look into it to figure out what is happening. Can you provide the SDK version you are using?

**Comment by botnerd** [comment]
We found the issue for the `Builder` class. We will have a fix in the next SDK release.

**Comment by hatched-mariusz** [comment]
> Thanks for reporting this. We'll look into it to figure out what is happening. Can you provide the SDK version you are using?

I notice that in the latest version 2.8.2 and previous too.
