### ISSUE TITLE
Public method are marked as restricted 

### ISSUE THREAD

**Issue by hatched-mariusz** [RadiusNetworks/flybuy-android#23]
The method getInstance() is marked as a restricted API, because of that I need to declare `@SuppressLint("RestrictedApi")` to avoid link error. 
```
PickupManager.getInstance()
```
Or the method should not be restricted or in the official documentation used as an initialization method. 

This is not only this one method -  there is a lot of methods like that

**Comment by botnerd** [comment]
This has been fixed in SDK v2.8.3
